name: Build NetHunter Kernel for d2s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Clone NetHunter builder
        run: git clone https://github.com/ravindu644/kali-nethunter-kernel.git

      - name: Configure NetHunter
        run: |
          cd kali-nethunter-kernel
          cat > local.config << 'EOF'
          ARCH=arm64
          SUBARCH=arm64
          KDIR=${{ github.workspace }}
          DEVICE=d2s
          DEFCONFIG=exynos9820-d2s_defconfig
          TOOLCHAIN=clang
          NH_VERSION=2025.3
          EOF

      - name: Build Kernel
        run: |
          cd kali-nethunter-kernel
          bash build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nethunter-d2s-OneUI4.1-boot
          path: kali-nethunter-kernel/output/*.img
